-- AKAN DIGUNAKAN UNTUK MEMASUKKAN DATA KE DALAM DATABASE 

-- ALTER TABLE UNTUK MODIFY AUTO INCREMENT
ALTER TABLE film AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE history AUTO_INCREMENT = 1;
ALTER TABLE pembelian AUTO_INCREMENT = 1;
ALTER TABLE bioskop AUTO_INCREMENT = 1;

-- DATA UNTUK DATABASE (TO BE UPDATED)
